### ISSUE TITLE
Still interested in maintaining?

### ISSUE THREAD

**Issue by seanfisk** [lvklabs/QSsh#9]
Hi, are you still interested in maintaining this library? If so, I might be able to help.

I'm looking for an SSH library for Qt and this appears to be a good candidate. However, it's not been updated to Qt 5 and I'm not sure it will compile out-of-the-box. However, what intrigues me is that it is based on source we *know* works (the Qt Creator SSH library).

I'd be willing to help extract/port the newest Qt Creator SSH library source to this library. What do you think? I've been an OSS maintainer and know how much work it is, so please don't feel badly about declining…

Either way, thank you for creating this library!

**Comment by paglian** [comment]
Hi Sean!

Thanks for reaching me out. Yes, I'm still interested. I haven't updated
this lib in a long time because I have not developed in Qt in a while. I
created this library for this project: https://github.com/lvklabs/chatbot
and it was used in a production environment successfully. So the library
indeed works ;)

I know the library does not compile in Qt5 (at least in some environemnts)
but it only requires minor changes to make it compile. Interested enough, I
received this pull request yesterday https://github.com/lvklabs/QSsh/pull/8
. I didn't have time to test it but I will. You can check it out.

Thanks for your help!

**Comment by seanfisk** [comment]
Thank you for the response, @paglian!

> I haven't updated this lib in a long time because I have not developed in Qt in a while.

Don't worry; I have been an OSS maintainer and completely understand this ;)

I'm excited to hear that you did use the library successfully in production. And yes, I did see that PR and will hopefully have time to check it out soon! Work is busy, but I'm hoping to be able to compile this and possibly make some contributions within the near future.

I'll close the ticket now, but look forward to corresponding soon. Thank you!
